#name: Lint and deploy
#
#on:
#  pull_request:
#  push:
#    branches:
#      - main
#
#jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#
#      - name: Install
#        yarn --frozen-lockfile --ignore-scripts
#
#      - name: Check typescript
#        make tslint
#
#      - name: Lint files
#        make eslint
#
#      - name: Build
#        make build
#
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./dist
