name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        yarn --frozen-lockfile

      - name: Lint files
        yarn run eslint

      - name: Check typescript
        yarn run tslint
